name: "Setup Anchor"
description: "Setup Anchor"

runs:
  using: "composite"
  steps:
    - uses: actions/cache@v3
      name: Cache Anchor Tool Suite
      id: cache-anchor
      with:
        path: |
          ~/.cache/anchor/
          ~/.local/share/anchor/
        key: anchor-${{ runner.os }}-v0000-${{ env.ANCHOR_VERSION }}
    - run: npm i -g @project-serum/anchor-cli@$ANCHOR_VERSION ts-mocha typescript
    # - run: cargo install --git https://github.com/project-serum/anchor avm --locked
    #   shell: bash
    # - run: sudo apt-get update && sudo apt-get upgrade && sudo apt-get install -y pkg-config build-essential libudev-dev
    #   shell: bash
    # - run: avm install ${{ env.ANCHOR_VERSION }}
    #   shell: bash
    # - run: avm use ${{ env.ANCHOR_VERSION }}
    #   shell: bash
