[package]
name = "trdelnik-client"
version = "0.3.0"
edition = "2021"
repository = "https://github.com/Ackee-Blockchain/trdelnik"
license-file = "../../LICENSE"
readme = "../../README.md"
description = "The trdelnik_client crate helps you build and deploy an Anchor program to a local cluster and run a test suite against it."

[build-dependencies]
vergen = { version = "6", features = ["build"], default-features = false }
anyhow = { version = "1.0.45", features = ["std"], default-features = false }

[dev-dependencies]
pretty_assertions = "1.1.0"

[dependencies]
trdelnik-test = { path = "../test", version = "0.2.0" }
solana-sdk = "1.14.7"
solana-cli-output = "1.14.7"
solana-transaction-status = "1.14.7"
solana-account-decoder = "1.14.7"
# TODO use official release once the version 0.25.0 is published with the newer solana (1.14.7)
# local build commit fad05805d8b3931169f1ca66253be310ce66ed2e
anchor-client = { path = "../../dependencies/anchor/client" }
spl-token = "3.5.0"
spl-associated-token-account = "1.1.1"
tokio = { version = "1.13.0", features = ["rt-multi-thread", "macros", "fs", "signal", "sync", "time", "io-util", "process"], default-features = false }
rand = "0.7.3"
serde_json = "1.0.72"
serde = "1.0.136"
bincode = "1.3.3"
borsh = "0.9.3"
futures = "0.3.18"
fehler = { version = "1.0.0", default-features = false }
thiserror = "1.0.30"
ed25519-dalek = "1.0.1"
serial_test = "0.5.1"
anyhow = { version = "1.0.45", features = ["std"], default-features = false }
cargo_metadata = "0.14.1"
syn = { version = "1.0.85", features = ["full"] }
quote = "1.0.14"
heck = { version = "0.4.0", default-features = false }
toml = { version = "0.5.8", features = ["preserve_order"] }
log = "0.4"
rstest = "0.12.0"
lazy_static = "1.4.0"
