on:
  workflow_dispatch:
  push:

name: Test Escrow and Turnstile

env:
  SOLANA_CLI_VERSION: 1.16.6
  ANCHOR_VERSION: 0.28.0

jobs:
  run_examples:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-rust/
      - uses: ./.github/actions/setup-solana/
      - uses: ./.github/actions/setup-anchor/
        id: rust-setup
      - uses: Swatinem/rust-cache@v2
        name: Cache Rust and it's packages
      - name: Build Escrow
        working-directory: examples/escrow
        run: anchor build
      - name: Test Escrow
        working-directory: examples/escrow
        run: cargo run --manifest-path ../../Cargo.toml test
      - name: Build Turnstile
        working-directory: examples/turnstile
        run: anchor build
      - name: Test Turnstile
        working-directory: examples/turnstile
        run: cargo run --manifest-path ../../Cargo.toml test
